function esc(x){return String(x??'').replace(/[<>&"']/g,m=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[m]))}
function fmt(v){if(!Number.isFinite(v))return '—';const a=Math.abs(v);return Number(v).toFixed(a>=100?1:a>=10?2:3).replace(/0+$/,'').replace(/\.$/,'')}
function n(v){return Number(v).toFixed(2)}
export function renderFlatPattern(svg,rec,{componentId=null,componentName='Деталь',theme='light',fileName=''}={}){
  const sm=(rec?.manufacturing?.sheetMetal?.components||[]).find(x=>x.componentId===componentId)||null;
  const dark=theme==='dark',workspace=dark?'#111827':'#eef2f6',ink='#101820',blue='#1769c2',muted='#5c6773',sheet='#fff';
  svg.setAttribute('viewBox','0 0 1200 760');
  let s=`<rect width="1200" height="760" fill="${workspace}"/><rect x="10" y="10" width="1180" height="740" fill="${sheet}"/><rect x="22" y="22" width="1156" height="716" fill="none" stroke="${ink}" stroke-width="1.8"/>`;
  s+=`<text x="55" y="58" fill="${ink}" font-family="system-ui" font-size="20" font-weight="800">Развёртка · ${esc(componentName)}</text>`;
  if(!sm){
    s+=`<g font-family="system-ui" text-anchor="middle"><text x="600" y="330" font-size="26" font-weight="800" fill="${ink}">Листовой металл не подтверждён</text><text x="600" y="370" font-size="15" fill="${muted}">Feature Recognition Core не нашёл устойчивую постоянную толщину и/или поверхности гибов.</text><text x="600" y="398" font-size="13" fill="${muted}">Для производства развёртка не генерируется, пока классификация не пройдёт порог.</text></g>`;
    svg.innerHTML=s;return;
  }
  const blank=sm.blank||{},L=Math.max(blank.length||1,.01),W=Math.max(blank.width||1,.01),box={x:90,y:130,w:760,h:430},scale=Math.min(box.w/L,box.h/W)*.82,dw=L*scale,dh=W*scale,x=box.x+(box.w-dw)/2,y=box.y+(box.h-dh)/2;
  s+=`<g font-family="system-ui"><rect x="${n(x)}" y="${n(y)}" width="${n(dw)}" height="${n(dh)}" fill="#fdfefe" stroke="${ink}" stroke-width="1.8"/>`;
  for(const [i,b] of (blank.bendLines||[]).entries()){const bx=x+dw*b.position;s+=`<line x1="${n(bx)}" y1="${n(y)}" x2="${n(bx)}" y2="${n(y+dh)}" stroke="${blue}" stroke-width="1.2" stroke-dasharray="12 5 2 5"/><text x="${n(bx+5)}" y="${n(y+16)}" fill="${blue}" font-size="10" font-weight="700">B${i+1} · ${fmt(b.angleDeg)}° · R${fmt(b.radius)}</text>`}
  const yDim=y+dh+35;s+=`<line x1="${n(x)}" y1="${n(y+dh)}" x2="${n(x)}" y2="${n(yDim+5)}" stroke="${blue}"/><line x1="${n(x+dw)}" y1="${n(y+dh)}" x2="${n(x+dw)}" y2="${n(yDim+5)}" stroke="${blue}"/><line x1="${n(x)}" y1="${n(yDim)}" x2="${n(x+dw)}" y2="${n(yDim)}" stroke="${blue}"/><text x="${n(x+dw/2)}" y="${n(yDim-7)}" text-anchor="middle" fill="${blue}" font-family="ui-monospace" font-size="13" font-weight="700">${fmt(L)}</text>`;
  const xDim=x-35;s+=`<line x1="${n(x)}" y1="${n(y)}" x2="${n(xDim-5)}" y2="${n(y)}" stroke="${blue}"/><line x1="${n(x)}" y1="${n(y+dh)}" x2="${n(xDim-5)}" y2="${n(y+dh)}" stroke="${blue}"/><line x1="${n(xDim)}" y1="${n(y)}" x2="${n(xDim)}" y2="${n(y+dh)}" stroke="${blue}"/><text x="${n(xDim-8)}" y="${n(y+dh/2)}" transform="rotate(-90 ${n(xDim-8)} ${n(y+dh/2)})" text-anchor="middle" fill="${blue}" font-family="ui-monospace" font-size="13" font-weight="700">${fmt(W)}</text>`;
  s+='</g>';
  s+=`<g font-family="system-ui"><text x="890" y="145" fill="${ink}" font-size="14" font-weight="800">Sheet Metal Recognition</text><text x="890" y="174" fill="${muted}" font-size="12">Толщина: <tspan fill="${ink}" font-weight="700">${fmt(sm.thickness)} mm</tspan></text><text x="890" y="198" fill="${muted}" font-size="12">Гибов: <tspan fill="${ink}" font-weight="700">${sm.bendCount||0}</tspan></text><text x="890" y="222" fill="${muted}" font-size="12">Площадь заготовки: <tspan fill="${ink}" font-weight="700">${fmt(blank.area)} mm²</tspan></text><text x="890" y="246" fill="${muted}" font-size="12">${sm.formType==='rolled'?'Метод: <tspan fill="'+ink+'" font-weight="700">Rср · дуга</tspan>':'K-factor: <tspan fill="'+ink+'" font-weight="700">0.40</tspan>'}</text>${sm.formType==='rolled'&&blank.neutralRadius?`<text x="890" y="270" fill="${muted}" font-size="12">Rср: <tspan fill="${ink}" font-weight="700">${fmt(blank.neutralRadius)} mm</tspan> · ${fmt(blank.sweepDeg)}°</text>`:''}<text x="890" y="300" fill="#b45309" font-size="11" font-weight="800">ALPHA · VERIFY BEFORE CUTTING</text><foreignObject x="888" y="316" width="250" height="145"><div xmlns="http://www.w3.org/1999/xhtml" style="font:11px/1.45 system-ui;color:#5c6773">${esc(sm.note||'')}</div></foreignObject></g>`;
  s+=`<g font-family="system-ui"><rect x="720" y="610" width="440" height="112" fill="none" stroke="${ink}"/><line x1="720" y1="650" x2="1160" y2="650" stroke="${ink}"/><text x="735" y="638" fill="${ink}" font-size="14" font-weight="800">${esc(componentName)}</text><text x="735" y="674" fill="${muted}" font-size="10">Развёртка · S=${fmt(sm.thickness)} · ${sm.bendCount||0} гиб.</text><text x="735" y="695" fill="${muted}" font-size="9">${esc(fileName)}</text><text x="1145" y="708" text-anchor="end" fill="${blue}" font-size="9" font-weight="800">FEATURE RECOGNITION CORE v2.0</text></g>`;
  svg.innerHTML=s;
}
